# Set up you use case parameters
use_case:
    testcase: "transfer"
    input_data: "random" # files, dir, random and custom supported.
    file_size: "15728640,31457280,47185920,57671680" # If INPUT_DATA=random is selected choose the file sizes
    files_directory: "./inputData"  # Set directory from which to take files if INPUT_DATA=files
    run_count: 3

# Set up Data Ingestion parameters
# TODO
dataIngestion:
    chunker: ""
    dag_layout: ""

# Set your network topology
#TODO
network:
    n_nodes: 4 # TOTAL NUMBER OF NODES
    n_leechers: 1 # NUMBER OF LEECHERS
    n_passive: 0    # NUMBER OF PASSIVE NODES.
    max_connection_rate: 100 # % OF CONNECTION FROM THE TOTAL NUMBER OF NODES ALLOWED
    churn_rate: 10 # % CHURN RATE OF THE NETWORK.

    # Set your nodes parameters
nodes:
    nodes_bandwidth: # PERCENTAGE OF NODES WITH X BANDWIDTH. (0.2, 150; 0.3, 100) = 20% 150MB; 30% 100MB; Rest default.
    nodes_latency:
    nodes_jitter:
    max_cpu:
    max_ram:

# Set your havoc parameters.
havoc:
    attack_type: ""
    malicious_nodes: ""
